### ISSUE TITLE
Issue finding addon/index.js

### ISSUE THREAD

**Issue by knownasilya** [NullVoxPopuli/ember-addon-migrator#31]
```sh
➜  ember-toggle git:(main) npx ember-addon-migrator

Unable to find "addon/index.js" entrypoint, empty entrypoint created
Error occurred
  You may want to reset your repository and try again.
  Errors encountered during migration are likely unrecoverable.
asString.replaceAll is not a function
(node:68675) UnhandledPromiseRejectionWarning: TypeError: asString.replaceAll is not a function
    at replaceIn (file:///Users/ilya/.npm/_npx/68675/lib/node_modules/ember-addon-migrator/src/test-app.js:223:29)
    at async updateFilesWithinTestApp (file:///Users/ilya/.npm/_npx/68675/lib/node_modules/ember-addon-migrator/src/test-app.js:71:3)
    at async migrateTestApp (file:///Users/ilya/.npm/_npx/68675/lib/node_modules/ember-addon-migrator/src/test-app.js:26:3)
    at async run (file:///Users/ilya/.npm/_npx/68675/lib/node_modules/ember-addon-migrator/src/index.js:60:5)
```

**Comment by knownasilya** [comment]
Ah, looks like that's not an error, the next line is which seems like https://github.com/NullVoxPopuli/ember-addon-migrator/issues/16
