### ISSUE TITLE
[!] Error: You must supply options.input to rollup

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-addon-migrator#4]
Not sure if the issue is here or somewhere else in the stack. So just to document:

```sh
❯ git clone git@gitlab.com:michal-bryxi/open-source/ember-intl-changeset-validations.git
...
❯ cd ember-intl-changeset-validations
...
❯ npx ember-addon-migrator@latest
🎉 Congratulations! Your addon is now formatted as a V2 addon!

Next steps:
 - run `yarn install`
 - run `yarn run lint:fix` in each workspace
 - test your addon in ./test-app
 - push up a branch
 - merge
 - release
 - party 🥳

❯ yarn install
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > ember-intl-changeset-validations > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > @embroider/webpack > @types/source-map@0.5.7: This is a stub types definition for source-map (https://github.com/mozilla/source-map). source-map provides its own type definitions, so you don't need @types/source-map installed!
warning workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > @embroider/webpack > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > ember-source > @babel/plugin-transform-block-scoping@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > ember-resolver > babel-plugin-debug-macros@0.3.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > @glimmer/component > ember-cli-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > ember-intl-changeset-validations > eslint-plugin-prettier@4.0.0" has unmet peer dependency "prettier@>=2.0.0".
warning "workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > @glimmer/component > ember-cli-typescript > @babel/plugin-transform-typescript@7.5.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > @glimmer/component > ember-compatibility-helpers > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > test-app > ember-load-initializers > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-8665d288-af4a-46d1-9de1-fc1950fb55ce > ember-intl-changeset-validations > @nullvoxpopuli/eslint-configs > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ yarn build
yarn run v1.22.17
$ yarn workspace ember-intl-changeset-validations build
$ concurrently 'npm:build:*'
[build:*docs]
[build:*docs] > ember-intl-changeset-validations@4.0.0 build:docs
[build:*docs] > cp ../README.md ./README.md
[build:*docs]
[build:*js]
[build:*js] > ember-intl-changeset-validations@4.0.0 build:js
[build:*js] > rollup -c ./rollup.config.js
[build:*js]
[build:*docs] npm run build:docs exited with code 0
[build:*js]
[build:*js]  → dist...
[build:*js] [!] Error: You must supply options.input to rollup
[build:*js] Error: You must supply options.input to rollup
[build:*js]     at Graph.generateModuleGraph (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/shared/rollup.js:22987:19)
[build:*js]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[build:*js]     at Graph.build (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/shared/rollup.js:22930:9)
[build:*js]     at rollupInternal (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/shared/rollup.js:23552:9)
[build:*js]     at build (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/bin/rollup:1530:20)
[build:*js]     at runRollup (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/bin/rollup:1677:21)
[build:*js]
[build:*js] npm run build:js exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/michal/.volta/tools/image/node/16.13.2/bin/node
Arguments: /Users/michal/.volta/tools/image/yarn/1.22.17/lib/cli.js build
Directory: /Users/michal/ember/ember-intl-changeset-validations/ember-intl-changeset-validations
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

- Pushed code after changes from ember-addon-migrator [here](https://gitlab.com/michal-bryxi/open-source/ember-intl-changeset-validations/-/merge_requests/119/diffs).

**Comment by NullVoxPopuli** [comment]
thanks for reporting!

 there is a bug right now where the js and ts detection is backwards :sweat_smile:

**Comment by NullVoxPopuli** [comment]
Try 1.1.2?

**Comment by MichalBryxi** [comment]
Seems the same :-/

```sh
❯ yarn install
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > ember-intl-changeset-validations > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > @embroider/webpack > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > @embroider/webpack > @types/source-map@0.5.7: This is a stub types definition for source-map (https://github.com/mozilla/source-map). source-map provides its own type definitions, so you don't need @types/source-map installed!
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > ember-source > @babel/plugin-transform-block-scoping@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > ember-resolver > babel-plugin-debug-macros@0.3.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > @glimmer/component > ember-cli-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > ember-intl-changeset-validations > eslint-plugin-prettier@4.0.0" has unmet peer dependency "prettier@>=2.0.0".
warning "workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > @glimmer/component > ember-cli-typescript > @babel/plugin-transform-typescript@7.5.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > @glimmer/component > ember-compatibility-helpers > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > test-app > ember-load-initializers > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-e74bb8bd-ad19-4c8b-b6a1-501b89d22676 > ember-intl-changeset-validations > @nullvoxpopuli/eslint-configs > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ yarn build
yarn run v1.22.17
$ yarn workspace ember-intl-changeset-validations build
$ concurrently 'npm:build:*'
[build:*js]
[build:*js] > ember-intl-changeset-validations@4.0.0 build:js
[build:*js] > rollup -c ./rollup.config.js
[build:*js]
[build:*docs]
[build:*docs] > ember-intl-changeset-validations@4.0.0 build:docs
[build:*docs] > cp ../README.md ./README.md
[build:*docs]
[build:*docs] npm run build:docs exited with code 0
[build:*js]
[build:*js]  → dist...
[build:*js] [!] Error: You must supply options.input to rollup
[build:*js] Error: You must supply options.input to rollup
[build:*js]     at Graph.generateModuleGraph (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/shared/rollup.js:22987:19)
[build:*js]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[build:*js]     at Graph.build (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/shared/rollup.js:22930:9)
[build:*js]     at rollupInternal (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/shared/rollup.js:23552:9)
[build:*js]     at build (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/bin/rollup:1530:20)
[build:*js]     at runRollup (/Users/michal/ember/ember-intl-changeset-validations/node_modules/rollup/dist/bin/rollup:1677:21)
[build:*js]
[build:*js] npm run build:js exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/michal/.volta/tools/image/node/16.13.2/bin/node
Arguments: /Users/michal/.volta/tools/image/yarn/1.22.17/lib/cli.js build
Directory: /Users/michal/ember/ember-intl-changeset-validations/ember-intl-changeset-validations
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I do _think_ that npx version of the package got updated:

```sh
❯ head ~/.npm/_npx/cd971582436d5e38/node_modules/ember-addon-migrator/package.json
{
  "name": "ember-addon-migrator",
  "description": "tool for migrating ember addons to the addon v2 format",
  "version": "1.1.2",
  "type": "module",
  "license": "MIT",
  "author": "NullVoxPopuli",
  "repository": {
    "url": "https://github.com/NullVoxPopuli/ember-addon-migrator",
    "type": "https",
````

**Comment by NullVoxPopuli** [comment]
can you try with `npx ember-addon-migrator@latest`?

**Comment by MichalBryxi** [comment]
Yes, sorry. That was there. I tried to wipe `npx` cache first to make sure it's now using `1.1.2`. I changed my previous comment to show that `npx ember-addon-migrator@latest` was executed and it installed latest version.

**Comment by NullVoxPopuli** [comment]
does your rollup config's publicEntrypoints options match the files in your addon?

**Comment by MichalBryxi** [comment]
I [don't think so](https://gitlab.com/michal-bryxi/open-source/ember-intl-changeset-validations/-/merge_requests/119/diffs#d52ed6980667699c13d0951dd2f294558cb5b932_0_17):

```js
...
    addon.publicEntrypoints(['components/**/*.js', 'index.js']),
...
```

- `components` folder exists only as `test-app/app/components/.gitkeep`
- there is no `index.js`

**Comment by NullVoxPopuli** [comment]
atm, the rollup config isn't dynamically configured.
_ideally_ that would happen, but it's not exactly easy to do the correct thing as people have different opinions on what should be public.

There are some changes needed in `@embroider/addon-dev` before I/we can implement the "most generic" thing to do for the rollup configs, but atm, you'll need to customize them yourself.
(same with appReexports)

> components folder exists only as test-app/app/components/.gitkeep

test-app doesn't matter with v2 addons :partying_face: 

> there is no index.js

should be fine, I think.

> https://github.com/NullVoxPopuli/ember-addon-migrator/issues/4

Looks like I forgot to add node_modules to the gitignore :sweat_smile:

**Comment by NullVoxPopuli** [comment]
Made some adjustments here for clarity: https://github.com/NullVoxPopuli/ember-addon-migrator/pull/7

**Comment by NullVoxPopuli** [comment]
try 1.1.3 :upside_down_face:

**Comment by MichalBryxi** [comment]
Ok, caaaan you give me a hint what is exapected in `publicEntrypoints`?

I put there: 

```js
addon.publicEntrypoints(['src/**/*.js']),
```

Because the only interesting files from the consuming app perspective are:

```
ember-intl-changeset-validations/src
├── instance-initializers
│   └── application.js
├── utils
│   └── application.js
└── validations
    └── messages.js
```

But `yarn install` still gives me:

```
[build:*js] [!] Error: You must supply options.input to rollup
[build:*js] Error: You must supply options.input to rollup
```

**Comment by NullVoxPopuli** [comment]
publciEntrypoints should have every file that can be imported by an app. it may not be _every_ file in `src`.

if only one file is needed to be imported by an app, you can specify the one file, and then rollup will combine everything so users can't import those private details.

files specified an appReexports _must_ be in publicEntrypoints.

if you still have that error, can you link a PR / repo?

**Comment by NullVoxPopuli** [comment]
Here is an addon I just did: https://github.com/NullVoxPopuli/ember-popperjs/pull/142
_I probs_ should have split the commits into:
 - transformation
 - manual adjustments
 
 :shrug: next time :partying_face:

**Comment by MichalBryxi** [comment]
:squints: This is ... weird. I read that `publicEntrypoints` is basically being translated to `options.input` so if the error complains about this then `publicEntrypoints` has to be wrong. The files there exist. It does not matter even if I comment `addon.publicEntrypoints()` and `addon.appReexports()` out. Same output.

- As you're releasing new versions [constantly updating MR is here](https://gitlab.com/michal-bryxi/open-source/ember-intl-changeset-validations/-/merge_requests/119/diffs)

**Comment by NullVoxPopuli** [comment]
Here are the needed changes: https://gitlab.com/michal-bryxi/open-source/ember-intl-changeset-validations/-/merge_requests/120/diffs#4f5849148e3f9910dbb911c8dd29f2640529d4d9

`src` is an implicit root, so when publicEntrypoints also contained `src`, rollup was looking for `src/src`, and nothing was found
